### ISSUE TITLE
Refactoring any property causes massive amount of keyframes added to rotations

### ISSUE THREAD

**Issue by wisteso** [s-m-k/Unity-Animation-Hierarchy-Editor#4]
Using Unity 5.1.1f1

![ahe_bug_before](https://cloud.githubusercontent.com/assets/2422123/8689219/7ec020ca-2a6a-11e5-8f0d-925808f74b72.png)

![ahe_bug_after](https://cloud.githubusercontent.com/assets/2422123/8689221/809d020a-2a6a-11e5-8c86-5ed99c97007a.png)

This happens when renaming (refactoring) any property. Changing the path of any property causes all rotations in the animation to be completely filled with keyframes.

(Great plugin otherwise, thanks for creating it)

**Comment by jt7777** [comment]
I second that. Would be great to see this fixed, it is a valuable tool!

**Comment by hybridherbst** [comment]
I second that. Would be great to see this fixed, it is a valuable tool!

**Comment by s-m-k** [comment]
I'll check it out when I have time (might take a while, I'm sort of busy now).

I hope it's not a Unity bug, since I remember having a similar issue without using the hierarchy editor.

**Comment by wisteso** [comment]
Very appreciated, SMK.  I put a good college try into trying the fix the issue myself, but haven't found any obvious bug so far. My only idea is that its part of the expected behavior described at...

http://docs.unity3d.com/412/Documentation/ScriptReference/AnimationUtility.GetEditorCurve.html

_"transform curves always get combined and their keyframes is always the union of all keyframe points"_ might mean that the curve gets basically "flattened"... though on the other hand, it only happens with rotations, and not position data.

All curves are "Editor Curves" as well. So its not an ObjectReferenceCurve VS EditorCurve issue, i think.

**Comment by erydeman** [comment]
I made a variant of the script that fixes this issue. See answer in this thread:
http://answers.unity3d.com/questions/662382/how-to-change-objects-hierarchy-level-in-animation.html

**Comment by tanoielis** [comment]
Does anyone know of a way to use this tool with some sort of find/replace?

**Comment by ShayBox** [comment]
Ah so that's why some of my animations have that...

**Comment by s-m-k** [comment]
I'm closing this issue since I haven't used Unity in years and I no longer maintain the project.
